# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Michael Darisse
tagline:          'Michael Darisse'
description:      'Economics PhD Student at Florida State University'
url:              https://michaeldarisse.github.io
baseurl:          #
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:          Michael Darisse
name:           'Michael Darisse'
email:          mdarisse@fsu.edu


paginate:         4
# paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
google_analytics:   UA-150989928-1

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
